version: "3.8"

services:
  lizmap:
    image: joysonestibeiro/lizmap-webmap:latest
    environment:
      LIZMAP_CACHEREDISDB: '1'
      LIZMAP_CACHEREDISHOST: redis
      LIZMAP_CACHESTORAGETYPE: redis
      LIZMAP_HOME: /srv/lizmap
      LIZMAP_WMSSERVERURL: http://map:8080/ows/
      LIZMAP_CONFIG_INCLUDE: /srv/etc
      PGSERVICEFILE: /srv/etc/pg_service.conf
      PGPASSFILE: /srv/etc/pgpass.conf
    volumes:
      - ./lizmap.dir/projects:/srv/projects
      - ./lizmap.dir/etc:/srv/etc:ro
      - ./lizmap.dir/var/lizmap-theme-config:/www/lizmap/var/lizmap-theme-config
      - ./lizmap.dir/var/lizmap-config:/www/lizmap/var/config
      - ./lizmap.dir/var/lizmap-db:/www/lizmap/var/db
      - ./lizmap.dir/var/lizmap-log:/www/lizmap/var/log
      - ./lizmap.dir/var/lizmap-modules:/www/lizmap/lizmap-modules
      - ./lizmap.dir/var/lizmap-my-packages:/www/lizmap/my-packages
      - ./lizmap.dir/www:/www/lizmap/www
    command:
      - php-fpm
    depends_on:
      postgis:
        condition: service_healthy
    restart: unless-stopped

  map:
    image: joysonestibeiro/qgis-map-server:latest
    environment:
      PGSERVICEFILE: /srv/etc/pg_service.conf
      PGSPASSFILE: /srv/etc/pgpass.conf
      QGIS_OPTIONS_PATH: /srv/etc/qgis
      QGIS_SERVER_LIZMAP_REVEAL_SETTINGS: 'yes'
      QGSRV_API_ENABLED_LIZMAP: 'yes'
      QGSRV_CACHE_SIZE: '20'
      QGSRV_CACHE_STRICT_CHECK: 'no'
      QGSRV_CACHE_ROOTDIR: /srv/projects
      QGSRV_LOGGING_LEVEL: DEBUG
      QGSRV_SERVER_PLUGINPATH: /srv/plugins
      QGSRV_SERVER_RESTARTMON: /srv/.qgis-restart
      QGSRV_SERVER_WORKERS: 2
    volumes:
      - ./lizmap.dir/projects:/srv/projects
      - ./lizmap.dir/plugins:/srv/plugins
      - ./lizmap.dir/wps-data:/srv/data
      - ./lizmap.dir/etc:/srv/etc:ro
    ports:
      - "8091:8080"
    restart: unless-stopped

  redis:
    image: redis:5-alpine
    volumes:
      - redis_data:/data

  web:
    image: nginx:alpine
    volumes:
      - ./lizmap.dir/etc/nginx.conf:/etc/nginx/nginx.conf
      - ./lizmap.dir/var/log/nginx:/var/log/nginx
      - ./lizmap.dir/var/nginx-cache:/var/cache/nginx
      - ./lizmap.dir:/srv/lizmap
    ports:
      - "8090:8080"
    depends_on:
      - lizmap

  postgis:
    image: 3liz/postgis:15-3
    environment:
      POSTGRES_PASSWORD: lizmap
      POSTGRES_LIZMAP_DB: lizmap
      POSTGRES_LIZMAP_USER: lizmap
      POSTGRES_LIZMAP_PASSWORD: lizmap
    volumes:
      - postgis_data:/var/lib/postgresql/data
      - ./lizmap.dir/etc/postgres.init.d:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d lizmap -q || exit 1"]
      interval: 10s
      timeout: 5s
      start_period: 60s

volumes:
  postgis_data:
  redis_data:
